protected/models/Ciclo.php
<?php

Yii::import('application.models._base.BaseCiclo');

// @TODO: No debería poder editar un ciclo que está bloqueado ????
class Ciclo extends BaseCiclo {

	public static function model($className = __CLASS__) {
		return parent::model($className);
	}

	public static function getActivoId() {
		return Helpers::qryScalar("select id from ciclo where activo = true");
	}

	public static function getActivoNombre() {
		return Helpers::qryScalar("select nombre from ciclo where activo = true");
	}

	public static function getActivo() {
		return Ciclo::model()->find('activo = true');
	}

  public static function esActual() {
    return self::getActivoId() === self::getCicloIdParaCargaDeNotas();
  }

	public static function getCicloIdParaCargaDeNotas() {
		$ciclo_id = Opcion::getOpcionText("ciclo_id", Null, "educativoNotas");
   if ($ciclo_id) {
     return Helpers::qryScalar("select id from ciclo where id = $ciclo_id");
   } else {
//     vd2(Helpers::qry("select * from ciclo where activo = 1"));
     return Helpers::qryScalar("select id from ciclo where activo = 1");
   }
	}

	public static function getCicloIdParaInformesEducativo($log = null) {
		$ciclo_id = Opcion::getOpcionText("ciclo_id", Null, "educativoInformes");
		if ($ciclo_id) {
			return Helpers::qryScalar("select id from ciclo where id = $ciclo_id");
		} else {
			return Helpers::qryScalar("select id from ciclo where activo = 1");
		}
	}

	public static function getCicloIdParaInformesAdmin($log = null) {
		$ciclo_id = Opcion::getOpcionText("ciclo_id", Null, "adminInformes");
		if ($ciclo_id) {
			return Helpers::qryScalar("select id from ciclo where id = $ciclo_id");
		} else {
			return Helpers::qryScalar("select id from ciclo where activo = 1");
		}
	}

	public static function getCicloParaCargaDeNotas() {
		$ciclo_id = self::getCicloIdParaCargaDeNotas();
		return Ciclo::model()->findByPk($ciclo_id);
	}

	public static function getCicloParaInformesEducativo() {
		$ciclo_id = self::getCicloIdParaInformesEducativo();
		return Ciclo::model()->findByPk($ciclo_id);
	}

	public static function getCicloNombreParaCargaDeNotas() {
		$ciclo = self::getCicloParaCargaDeNotas();
		return $ciclo->nombre;
	}

}

protected/controllers/CicloController.php
<?php

class CicloController extends Controller {

  public $layout = "nuevo";

	public function actionIndex(){
		$this->pageTitle = "Ciclos por defecto";
		$this->render("index");
	}
	
	public function actionGraba(){
		$ret = new stdClass();
		$user_id = Yii::app()->user->id;
		$ciclo_id_para_informes_educativo = $_POST['ciclo_id_para_informes_educativo'];
		$ciclo_id_para_informes_admin = $_POST['ciclo_id_para_informes_admin'];
		$ciclo_id_actual = Ciclo::getActivoId();
//		if($ciclo_id_actual === $ciclo_id_para_informes){
//			Opcion::deleteOpcion('ciclo_id', "educativoInformes");
//		}else{
//		}
			Opcion::saveOpcion('ciclo_id', $ciclo_id_para_informes_educativo, "educativoInformes");
			Opcion::saveOpcion('ciclo_id', $ciclo_id_para_informes_admin, "adminInformes");
		$ret->status = 'ok';
		echo json_encode($ret);
	}

}

?>

protected/views/ciclo/index.js.php
<?php 
	$ciclo_id_para_informes_global_educativo = Helpers::qryScalar(""
			. "select data "
			. "from opcion where nombre = 'ciclo_id' and categoria = 'educativoInformes' and user_id is null"
			);
	if(!$ciclo_id_para_informes_global_educativo){
		$ciclo_id_para_informes_global_educativo = Ciclo::getCicloIdParaInformesEducativo();
	}
	
	$ciclo_id_para_informes_global_admin = Helpers::qryScalar(""
			. "select data "
			. "from opcion where nombre = 'ciclo_id' and categoria = 'adminInformes' and user_id is null"
			);
	if(!$ciclo_id_para_informes_global_admin){
		$ciclo_id_para_informes_global_admin = Ciclo::getCicloIdParaInformesAdmin();
	}
	
	
	$ciclo_nombre_para_informes_global_educativo = Helpers::qryScalar(""
			. "select nombre from ciclo where id = $ciclo_id_para_informes_global_educativo");

	$ciclo_nombre_para_informes_global_admin = Helpers::qryScalar(""
			. "select nombre from ciclo where id = $ciclo_id_para_informes_global_admin");
	?>
	
<script>
	var vm = (function () {
			var vm = {};
			vm.data = {};
			vm.data.ciclo_id_para_informes_educativo = ko.observable(<?php echo Ciclo::getCicloIdParaInformesEducativo() ?>);
			vm.data.ciclo_id_para_informes_admin = ko.observable(<?php echo Ciclo::getCicloIdParaInformesAdmin() ?>);
			vm.ciclo_nombre_para_informes_global_educativo = ko.observable(<?php echo $ciclo_nombre_para_informes_global_educativo ?>);
			vm.ciclo_nombre_para_informes_global_admin = ko.observable(<?php echo $ciclo_nombre_para_informes_global_admin ?>);
			vm.ciclo_activo_nombre = ko.observable("<?php echo Ciclo::getActivoNombre() ?>");
			vm.init = function () {
					console.log('init');
			};
			return vm;
	})();
	vm.cancel = function(){
		window.location.reload();
	}
	vm.submit = function () {
		var data = ko.mapping.toJS(vm.data);
			$.ajax({
					type: "POST",
					dataType: "json",
					data: data,
					//data: $("form").serialize(),
					url: "<?php echo $this->createUrl("/ciclo/graba"); ?>",
					success: function (data) {
							toastr.info("Los datos fueron guardados",null,{timeOut:2500});
							console.log('ok');
					},
					error: function (data, status) {
						console.log('error', data, status);
					}
			}
			);
	};
	vm.init();

</script>

protected/views/ciclo/index.php
<?php include("index.js.php"); ?>
<div class='container top20'>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4>Ciclos por defecto</h4>
			<!--<span data-bind="text:'El ciclo activo es ' + ciclo_nombre_para_informes_global_educativo()"></span>-->
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-12 top20">
					<form class="form" data-bind="submit: submit">
						<fieldset>
							<legend>Educativo</legend>
								<div class='form-group form-inline'>
									<?php $op = array("class" => "form-control"); ?>
									<?php $ld = CHtml::listData(Ciclo::model()->findAll(), 'id', "nombre"); ?>
									<?php $lo = CHtml::listOptions(3, $ld, $op); ?>
									<label for='ciclo'>Ciclo para Informes:</label>
									<select class="form-control" data-bind="value: data.ciclo_id_para_informes_educativo">
										<?php echo $lo; ?>
									</select>
									<code data-bind="text:'Global: ' + ciclo_nombre_para_informes_global_educativo()" class="help-block" style="width:150px;display:inline"></code>
								</div>
						</fieldset>
						<hl></hl>
						<fieldset>
							<legend>Administrativo</legend>
								<div class='form-group form-inline'>
									<?php $op = array("class" => "form-control"); ?>
									<?php $ld = CHtml::listData(Ciclo::model()->findAll(), 'id', "nombre"); ?>
									<?php $lo = CHtml::listOptions(3, $ld, $op); ?>
									<label for='ciclo'>Ciclo para Informes:</label>
									<select class="form-control" data-bind="value: data.ciclo_id_para_informes_admin">
										<?php echo $lo; ?>
									</select>
									<code data-bind="text:'Global: ' + ciclo_nombre_para_informes_global_admin()" class="help-block" style="width:150px;display:inline"></code>
								</div>
						</fieldset>
						<!--		<fieldset class="top20">
									<legend>Administrativo</legend>
									<div class="col-sm-4 control-group">
										<div class='form-group'>
											<label for='ciclo'>Ciclo para carga de notas:</label>
										</div>
									</div>
								</fieldset>-->
						<div class="btn-group pull-right">
							<button data-bind="click: cancel" class="btn btn-small btn-default">Cancela</button>
							<button type="submit" class="btn btn-small btn-primary">Graba</button>
						</div>
						<div class="row">
							<div class="col-xs-2">
								<input type="text" class="form-control" placeholder=".col-xs-2">
								<p class="help-block">First Name</p>
							</div>
							<div class="col-xs-3">
								<input type="text" class="form-control" placeholder=".col-xs-3">
								<p class="help-block">M.I</p>
							</div>
							<div class="col-xs-4">
								<input type="text" class="form-control" placeholder=".col-xs-4">
								<p class="help-block">Last</p>
							</div>
						</div>
					</form>
				</div>
			</div>
			<span data-bind="text: vm.ciclo_id"></span>
		</div>
	</div>
</div>
	<script>
		ko.applyBindings(vm);
	</script>